Gemfile.lock, lib/hocon/impl/parser.rb
Fix a NameError that would occur when a string containing
{\n} was parsed.
=> Fix NameError when parsing {\n}

Gemfile.lock, lib/hocon/impl/parser.rb, lib/hocon/impl/path.rb, spec/fixtures/parse_render/example3/input.json, spec/fixtures/parse_render/example3/output.conf, spec/spec_helper.rb, spec/unit/typesafe/config/config_factory_spec.rb
Allow the ruby hocon gem to parse JSON files. Previously,
attempting to parse a JSON file would lead to an uninitialized
constant error.
=> Allow gem to parse JSON files

Gemfile.lock, lib/hocon/impl/abstract_config_value.rb, lib/hocon/impl/config_float.rb, lib/hocon/impl/config_null.rb, lib/hocon/impl/token.rb, lib/hocon/impl/tokenizer.rb, lib/hocon/impl/tokens.rb, spec/test_utils.rb, spec/unit/typesafe/config/tokenizer_spec.rb
Ported all the java tests from the hocon library to ruby-hocon
Added a few more here and there
Implemented misc missing functions from the java library to get the tests passing
Fixed bug in tokenizer that ignored whitespace between tokens
=> (TK-155) Port tokenizer tests to ruby hocon

lib/hocon/impl/parser.rb, lib/hocon/impl/tokenizer.rb, spec/fixtures/parse_render/example2/input.conf, spec/fixtures/parse_render/example2/output.conf, spec/fixtures/parse_render/example2/output_nocomments.conf, spec/spec_helper.rb, spec/unit/typesafe/config/hocon_spec.rb
This commit fixes the tokenization of unquoted strings which might be
numbers.  In particular, this affects IP addresses.
The tokenizer aggressively attempts to parse such strings as
either a Float or Integer and relies on an error being raised to
indicate when the string is not actually a valid number.  However,
`to_i` and `to_f` never raise execptions, so the constructors must be
used instead.
=> (TK-128) fix tokenization of unquoted strings

lib/hocon/impl/parser.rb, lib/hocon/impl/token.rb, lib/hocon/impl/token_type.rb, lib/hocon/impl/tokenizer.rb, lib/hocon/impl/tokens.rb, spec/test_utils.rb, spec/unit/typesafe/config/tokenizer_spec.rb
This is a direct port of the following PR: https://github.com/typesafehub/config/pull/271
As described in the above PR, this allows Tokens to keep track of the original text from which they were parsed. It also adds a new IgnoredWhitespace token to represent whitespace ignored by the parser that was previously thrown out when tokenizing input. Finally, a render() method has been added to the TokenIterator class, which reproduces the original input text.
=> Add lossless comment tokens

lib/hocon/config_parse_options.rb, lib/hocon/impl/parseable.rb, lib/hocon/impl/parser.rb, lib/hocon/impl/simple_config_origin.rb, lib/hocon/impl/tokenizer.rb, spec/test_utils.rb
Rename methods whose names start with "set_" or "with_" to match
the names of these methods in the upstream Java project.
@jpinsonault and I discussed this the other day.
=> (maint) rename methods to match upstream

lib/hocon/impl/config_concatenation.rb, lib/hocon/impl/config_delayed_merge.rb, lib/hocon/impl/config_delayed_merge_object.rb, lib/hocon/impl/config_impl.rb, lib/hocon/impl/config_reference.rb, lib/hocon/impl/default_transformer.rb, lib/hocon/impl/replaceable_merge_stack.rb, lib/hocon/impl/simple_config.rb, lib/hocon/impl/simple_config_list.rb, lib/hocon/impl/simple_config_object.rb, lib/hocon/impl/simple_config_origin.rb, lib/hocon/impl/substitution_expression.rb, spec/test_utils.rb, spec/unit/typesafe/config/config_value_spec.rb
This is a partial set of the tests for ConfigValueTest.scala
We're going to get whatever functionality I've implemented in this PR so others can use it and
avoid creating merge conflicts.
The rest of the PRs will come as much smaller chunks of effort
This branch was rebased on top of @KevinCorcoran's tk-162 PR, and hopefully I merged my changes into it without breaking anything the tests didn't catch.
Implemented parts of:
ConfigDelayedMerge
ConfigDelayedMergeObject
ConfigReference
ReplaceableMergeStack module
SimpleConfigList/Object now behave like arrays/hashes by delegating required functions to their @value attribute
Implemented ==() and hash() for a bunch of classes
Many other small changes
=> (TK-159) Partial set of ConfigValue tests implemented

lib/hocon/config_error.rb, lib/hocon/config_parse_options.rb, lib/hocon/config_value_type.rb, lib/hocon/impl/abstract_config_object.rb, lib/hocon/impl/abstract_config_value.rb, lib/hocon/impl/config_concatenation.rb, lib/hocon/impl/config_impl.rb, lib/hocon/impl/parser.rb, lib/hocon/impl/path_builder.rb, lib/hocon/impl/properties_parser.rb, lib/hocon/impl/resolve_source.rb, lib/hocon/impl/simple_config_list.rb, lib/hocon/impl/simple_config_object.rb, lib/hocon/impl/simple_config_origin.rb, lib/hocon/impl/simple_include_context.rb, lib/hocon/impl/simple_includer.rb, lib/hocon/impl/token_type.rb, lib/hocon/impl/tokenizer.rb, lib/hocon/impl/tokens.rb, lib/hocon/impl/url.rb, spec/test_utils.rb
This commit re-enables some disabled config parser tests that
had been failing due to missing functionality around HOCON's
`include` capabilities.  It also includes a minimal port
of all of the `include` functionality that was required
to get the tests passing.
=> (TK-160) Port minimal `include` functionality

lib/hocon/impl/abstract_config_object.rb, lib/hocon/impl/abstract_config_value.rb, lib/hocon/impl/simple_config_object.rb, spec/unit/typesafe/config/config_value_spec.rb
This commit cleans up the order of the code in `SimpleConfigObject` to more closely mirror that of the upstream, and also ports over a bunch of stuff that hadn't been ported yet.
=> (MAINT) flesh out simple config object

lib/hocon/config_render_options.rb, lib/hocon/impl/abstract_config_object.rb, lib/hocon/impl/abstract_config_value.rb, lib/hocon/impl/config_boolean.rb, lib/hocon/impl/config_concatenation.rb, lib/hocon/impl/config_delayed_merge.rb, lib/hocon/impl/config_delayed_merge_object.rb, lib/hocon/impl/default_transformer.rb, lib/hocon/impl/parser.rb, lib/hocon/impl/simple_config.rb, lib/hocon/impl/simple_config_list.rb, lib/hocon/impl/simple_config_object.rb, lib/hocon/impl/simple_config_origin.rb, lib/hocon/impl/tokens.rb, spec/test_utils.rb, spec/unit/typesafe/config/config_value_spec.rb
Another set of tests for config_value_spec. There will be at least one more after this one.
Added a few methods to AbstractConfigObject
Made the definitions of merge_origins static to match the java
Implemented render/render_to_sb methods for ConfigDelayedMerge
Fixed DefaultTransformer::transform method to actually compare the value type
Made SimpleConfigObject::indent static
SimpleConfigOrigin::merge_origins handles merging more than two tokens correctly
Implemented SimpleConfigOrigin#filename using @cprice404's Url class
A couple methods in tokens.rb
get_substitution_path_expression
get_substitution_optional
Commented out some failing tests in conf_parser_spec until some missing functionality is implmented
=> (TK-159) Round Two of ConfigValue tests

lib/hocon/impl/abstract_config_value.rb, lib/hocon/impl/config_concatenation.rb, lib/hocon/impl/config_delayed_merge_object.rb, lib/hocon/impl/parseable.rb, lib/hocon/impl/parser.rb, lib/hocon/impl/path.rb, lib/hocon/impl/path_builder.rb, lib/hocon/impl/path_parser.rb, lib/hocon/impl/resolve_result.rb, lib/hocon/impl/resolve_source.rb, lib/hocon/impl/simple_config_list.rb, lib/hocon/impl/simple_config_object.rb, lib/hocon/impl/simple_config_origin.rb, spec/unit/typesafe/config/concatenation_spec.rb
Un-comment the remaining concatenation test cases that were still commented-out
and fix bugs.  Also added 'inspect' implementations and use short class names to
make trace output match upstream, and re-wrote various bits of code to correspond
more closely to upstream.
=> (TK-162) enable concatenation test cases + fixes

lib/hocon/impl/abstract_config_node.rb, lib/hocon/impl/abstract_config_node_value.rb, lib/hocon/impl/config_node_array.rb, lib/hocon/impl/config_node_comment.rb, lib/hocon/impl/config_node_complex_value.rb, lib/hocon/impl/config_node_concatenation.rb, lib/hocon/impl/config_node_field.rb, lib/hocon/impl/config_node_include.rb, lib/hocon/impl/config_node_object.rb, lib/hocon/impl/config_node_path.rb, lib/hocon/impl/config_node_root.rb, lib/hocon/impl/config_node_simple_value.rb, lib/hocon/impl/config_node_single_token.rb, lib/hocon/impl/parser.rb, lib/hocon/impl/path.rb, lib/hocon/impl/path_parser.rb, lib/hocon/impl/tokens.rb, lib/hocon/parser.rb, lib/hocon/parser/config_node.rb, spec/test_utils.rb, spec/unit/typesafe/config/concatenation_spec.rb, spec/unit/typesafe/config/config_node_spec.rb
Some of the implementation of this is a bit different from what's in master at the time of this writing. This is due to the fact that, when porting these tests, I discovered some issues with the upstream tests that needed to be fixed/cleaned up. This PR contains the tests in the upstream master branch, along with the changes I've made in https://github.com/typesafehub/config/pull/301.
=> (TK-186) Port ConfigNode tests

Gemfile.lock, lib/hocon/impl/simple_config_document.rb, spec/unit/typesafe/config/config_document_spec.rb
Add a test for insertion into an empty ConfigDocument.
I decided to add this because it's a valid use case (we're using it in the hocon module) and because it's broken in the upstream
=> (MAINT) Add empty document insertion test

lib/hocon/impl/tokens.rb
Prior to this commit, the `Problem` token type called
`to_s` on an internal `StringIO` object when building
up an error string to return to the user.  Calling
`to_s` on a `StringIO` just causes it to print out,
basically, `#<StringIO...>`, so you don't get the
useful error message.
This patch changes the code to call `string` instead,
which returns a much more useful error message.
=> (MAINT) Improve error messages for Problem tokens

lib/hocon/impl/config_node_object.rb, spec/unit/typesafe/config/config_document_spec.rb, spec/unit/typesafe/config/config_node_spec.rb
Previously there was a bug wherein building out a config starting
from an empty ConfigDocument would cause the entire config to
exist on a single line. Fix this bug by modifying the addition of
new maps along a path to add multi-line maps instead of
single-line maps if the object being added to is an empty root or
a multi-line object.
This PR is based on https://github.com/typesafehub/config/pull/333.
=> (TK-246) Fix single-line config bug

Gemfile.lock, lib/hocon/impl/config_node_object.rb, spec/unit/typesafe/config/config_document_spec.rb
Fix an undefined method bug that was occurring when attempting to
add a complex value into an empty root object.
This is a port of https://github.com/typesafehub/config/pull/334
=> (MAINT) Fix undefined method bug

lib/hocon/impl/simple_config_document.rb, spec/unit/typesafe/config/config_document_spec.rb
Remove unnecessary "# hardcoded value" comments that were being
generated when inserting a hash or an array into a ConfigDocument.
=> (TK-249) Remove unnecessary comments in output

Gemfile.lock, lib/hocon/config_value_factory.rb, spec/unit/typesafe/config/config_value_factory_spec.rb
When parsing a Hash in ConfigValueFactory, automatically convert
all symbol keys to strings.
=> (TK-251) Convert symbol keys to strings

README.md, lib/hocon.rb, lib/hocon/impl/config_reference.rb
This commit updates the README to show the simpler version of the
API for basic read operations.
It also fixes some circular dependencies that were causing the
example code for the ConfigDocumentFactory not to work properly.
=> (HC-24) Use simple API in README, fix circular deps

lib/hocon/impl/simple_config_origin.rb
This causes an error when calling resolve on a parsed config `Hocon::ConfigFactory.parse_file(config_file).resolve`
=> Fix typo when referencing GENERIC OriginType

CHANGELOG.md, Gemfile.lock, README.md, hocon.gemspec
0.9.4 introduced changes that require some users to modify their require
statements due to bugfixes. In addition the API is stable enough to consider this a 1.0.0
release
1.0.0 Changlog:
This is a bugfix release.
The API is stable enough and the code is being used in production, so the version is also being bumped to 1.0.0
* Fixed a bug wherein calling "Hocon.load" would not
resolve substitutions.
* Fixed a circular dependency between the Hocon and Hocon::ConfigFactory
namespaces. Using the Hocon::ConfigFactory class now requires you to
use a `require 'hocon/config_factory'` instead of `require hocon`
* Add support for hashes with keyword keys
**Easier to look at just the first commit** without the whitespace changes in the readme
=> (MAINT) bump and relabel version 0.9.4 to 1.0.0

lib/hocon/config_value_type.rb, lib/hocon/impl/from_map_mode.rb, lib/hocon/impl/parseable.rb, lib/hocon/impl/simple_config.rb, lib/hocon/impl/token.rb, lib/hocon/impl/token_type.rb, lib/hocon/impl/tokens.rb
Prior to this commit, there were a few places in the code where
we'd ported over a class-or-module-level method named `name` from
the upstream library.  This isn't a good idea in Ruby because it
results in shadowing of the built in Ruby methods Class#name and
Module#name.  This was causing problems for some users, e.g. in
cases where reflection is being used to examine classes.
In this commit we rename all such methods to something more specific,
and replace the calls to the old names with calls to the new names.
=> (HC-80) Don't shadow ruby Class/Module#name method

lib/hocon/impl/parseable.rb, lib/hocon/impl/simple_config.rb, lib/hocon/impl/tokens.rb, spec/unit/hocon/hocon_spec.rb
This repo currently does not consistently and correctly use calls to `value_type_name`, causing undefined method errors. This PR fixes all calls to correctly call the module/class method rather than an instance method which does not exist. This PR also adds two spec tests to make sure that it is correctly attempting to parse arrays and throwing a ConfigWrongTypeError.
=> (HC-81) Fix undefined method `value_type_name' error

CHANGELOG.md, lib/hocon/version.rb
The release job needs to take in the new version number, and that version has to be greater than the version currently in the project. Ruby interprets `1.2.0-SNAPSHOT` as lower than `1.2.0`, so this should work
=> (MAINT) Update version and changelog for 1.2.0 release

Gemfile, lib/hocon/impl/simple_config_origin.rb, spec/unit/typesafe/config/conf_parser_spec.rb
Prior to this change, the hocon parser would
error when give file names like ᚠᛇᚻ.conf or
/tmp/旗本/pe.conf.
This commit URI encodes the filenames to
avoid that issue.
=> (PE-18165) encode file URIs to handle utf8 chars

CHANGELOG.md, Gemfile, lib/hocon/impl/simple_config_origin.rb, lib/hocon/version.rb
This commit removes the dependency on Addressable and adds some comments
regarding some screwy areas in the code where we half heartedly tried to
support loading of URIs
It maintains utf-8 file support
=> (PE-18165) Support for utf-8 file paths

lib/hocon/impl/config_impl.rb, spec/fixtures/hocon/with_substitution/subst.conf, spec/spec_helper.rb, spec/unit/hocon/hocon_spec.rb
- https://github.com/lightbend/config/pull/427 added support to the
Java version of Hocon for lists of environment variables.
For instance, given a Hocon configuration file like:
"a": ${testList}
And the environment variables:
testList.0=0
testList.1=1
Then the Hocon configuration file will resolve to the values:
"a": ["0", "1"]
- Implement the behavior in the Ruby code and add specs demonstrating
this new behavior
This is needed to support https://github.com/puppetlabs/pe-bolt-vanagon/pull/35
=> (HC-104) Support environment variable lists

lib/hocon/impl/parseable.rb
This is threadlocal in the Java version and I assume was made into a class
variable because at the time we didn't have any multithreaded environment. When
used with threads this stack becomes corrupt.
=> (HC-105) Make parse stack threadlocal

lib/hocon/impl/parseable.rb
File.exists? is already deprecated since ruby 2.1 and will be removed with ruby 3.2. Replace this with File.exist? .
Fixes #126 .
=> (maint) replace File.exists? with File.exist for ruby3.2

hocon.gemspec
That allows tools to correctly pick it up
=> Use the correct SPDX ID for the Apache v2 license

.github/workflows/mend.yaml, .github/workflows/rspec_tests.yaml
The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.
=> (PA-5796) Update Checkout GitHub Action
